### ISSUE TITLE
serial package requirement issue

### ISSUE THREAD

**Issue by onkelandy** [Morg42/plugins#1]
Problem beim Start Plugin 'squeezebox' error importing Python package: No module named 'serial' Könnte man das anpassen, dass serial Modul nur dann gefordert wird, wenn es vom Plugin gebraucht/unterstützt wird? Alternativ in die requirements vom core stecken?

**Comment by onkelandy** [comment]
Kommentar von Msinn zum Einfügen des Requirements im Core:
Das halte ich für keine gute Idee. Die Requirements sollten schon da angegeben werden, wo sie benutzt werden, also bei dem jeweiligen Plugin.

**Comment by Morg42** [comment]
proposed fix online, please test
