### ISSUE TITLE
potential feature request: have one plugin for one device with multiple protocols

### ISSUE THREAD

**Issue by onkelandy** [Morg42/plugins#3]
Logitech Media Server supports CLI/net_tcp device and jsonrpc. Maybe it is possible to somehow combine both to just have one plugin?
Commands could be read based on protocol configuration, e.g. having separate dicts in commands.py. If protocols support different information, = having different items in the struct, there might be some issue, however.

**Comment by Morg42** [comment]
A possible solution might be to write a generic plugin and offload protocol-specific work to a separate protocol-layer (also see sdp_viessmann for P300 / KW2)?

**Comment by onkelandy** [comment]
Not 100% sure if I can follow... Could/should the different commands just be put in the same commands.py as two different "models"?

**Comment by Morg42** [comment]
Fix for potential solution implemented.

**Comment by onkelandy** [comment]
this is actually closely related to issue #9 
In general this works by implementing multiple protocols for the plugin, having two "trees" in the commands.py.
However, having individual structs such as lms/cli/player and lms/json/player is not supported/working. I close this anyhow.
