### ISSUE TITLE
sdp plugins: update multiple items with same response

### ISSUE THREAD

**Issue by onkelandy** [Morg42/plugins#5]
Example response: `b8:27:eb:a3:29:99 playlistcontrol cmd:load playlist_id:277228 noEdit:0 count:38`

commands.py: 
```
Count: r'{CUSTOM_ATTR1} playlistcontrol cmd:load . count:(\d+)'
ID: r'{CUSTOM_ATTR1} (?:status - 1 .|playlist playlistsinfo |playlistcontrol cmd:load playlist_)id:(\d+)'
```

Currently when receiving given response only one command (ID or Count, depending on order) gets evaluated. I'd expect both commands being evaluated (at least when activating some option or similar). 
Because there are multiple ways to update the ID for example it is quite cumbersome to use the _process_additional_data for dissecting the received data and updating the other command manually (in this example count)

**Comment by Morg42** [comment]
Possible fix inserted, pls. give feedback

**Comment by onkelandy** [comment]
works, thx!
